### ISSUE TITLE
Login Error

### ISSUE THREAD

**Issue by Question4ble** [Legomaniak/MNF#6]
Application has been working basically fine up to today (application last ran less than a day ago) since I first got it running, but now I am encountering login errors. Here's the last handful of lines I was given:

> Download avatar.swf
> Loging to game
> System.IndexOutOfRange Exception: Index was outside the bounds of the array.
> 	at Mnf.MnfLogger.UserParse(String s) in \MnfPic-master\MnfPic-master\Mnf\MnfLogger.xaml.cs:line 247

and then there's a pop-up error reading

> Bad login
> &errors=3&

I know that there was a previous, somewhat similar issue that was resolved where the user wasn't using the up-to-date application, so I attempted to download and run the application upload from April, but I am getting the same issue and error text.

EDIT/FOLLOW-UP
Turns out the account I was using to farm with (which was a throwaway anyway) got blocked. And also the other account that I was using as an in-between that it was moving its money to. Looks like they took notice for some reason. I guess this is now more of a report in than an issue. To clarify how I was trying to keep my tracks covered, I was farming on one account, sending it to another via stripper pole donations, and then banking it over to another's avatars. Looks like it was an IP ban though, since it also killed some of my other spare accounts that weren't involved. No softball being played here.

**Comment by Legomaniak** [comment]
We register a lot off login issue for past two weeks, even with regular client. After they will have stable server again, we can make improvements.
Admins control any suspicious behaviour and pole dance money transfer isn't safe in case if you use a lot of chars/accounts from one IP. 
Idea is using farmer on main acc based on random daily farming with low chance to get into highscore.

**Comment by Question4ble** [comment]
Thanks for the reply. No real damage done over here, just wanted to let you know.
